### PR TITLE
Update kondo

### PR DESCRIPTION
**Pull request by TsubasaK111**
@takayukioda review me!

### CODE REVIEW

**Comment by TsubasaK111** [comment]
FYI @koka831

**Comment by takayukioda** [comment]
ummm, why using `argparse`?
I removed those argument parsing libraries because some of those libraries change the input value; I experienced in nodejs turn `012349` to `12349` and got one test case become error for all the time.
I would like to have those part simple as much as possible.

**Comment by takayukioda** [comment]
Sorry, forgot to mention you
@TsubasaK111

**Comment by TsubasaK111** [comment]
@takayukioda You're right. I reverted to the non-argparse implementation and I did the same for Python2. Review me again!

**Review by takayukioda — APPROVED** [review]
https://media.giphy.com/media/26uffErnoIpeQ3PmU/giphy.gif

**Pull request merged**
